# DeepSeek API 키
DEEPSEEK_API_KEY = "sk-4da73f3de0b24cb584fe9c946730b372"

# Supabase API 키
SUPABASE_URL = "https://neiweeotgdbqtixsrfxn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5laXdlZW90Z2RicXRpeHNyZnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MzE3MjMsImV4cCI6MjA3ODEwNzcyM30._Qf2rUmoTUfLCwwsMYnCCC0SuL-CukavQ1Gm0zOyJCs"

# 교사용 간편 암호
TEACHER_PASSWORD = "우리반비밀번호123"