# DeepSeek API 키
DEEPSEEK_API_KEY = "sk-4da73f3de0b24cb584fe9c946730b372"

# Supabase API 키
SUPABASE_URL = "https://xxxxxxxxx.supabase.co"
SUPABASE_KEY = "eyxxxxxxxxxxxxxxxxxxxxxx"

# 교사용 간편 암호
TEACHER_PASSWORD = "우리반비밀번호123"